# Generated by Django 5.0.4 on 2024-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courseschedule_id_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='room_number',
            field=models.CharField(choices=[('sunday, tuesday, thursday', 'sunday, tuesday, thursday'), ('monday, wednesday', 'monday, wednesday')], max_length=100),
        ),
    ]
