# Generated by Django 5.0.4 on 2024-05-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='user',
        ),
    ]
