# Generated by Django 5.0.4 on 2024-05-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_notification_delete_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('registration', 'Registration Deadline'), ('drop_add', 'Drop/Add Deadline')], max_length=20)),
                ('description', models.TextField()),
                ('deadline_date', models.DateField()),
            ],
        ),
    ]
