# Generated by Django 5.0.4 on 2024-05-22 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_deadline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
